### PR TITLE
fix: allow closing flow seq/map at same indentation

### PR DESCRIPTION
**Pull request by rliebz**
The commit as written does not include running tree-sitter generate. Happy to run that if someone can point me to the documentation for how that can be done for the current iteration of the repo.

For reference, here is a working version of the fix from before the repo was forked: https://github.com/rliebz/tree-sitter-yaml/commit/c1c2506543eb99abe0a0f305428b6432c71b30c0

Resolves: https://github.com/ikatyang/tree-sitter-yaml/issues/29
Relates-to: https://github.com/tree-sitter-grammars/tree-sitter-yaml/issues/2

### CODE REVIEW

**Comment by rliebz** [comment]
@clason Rebased with your change from #2, ran `tree-sitter generate`, and should be good to go!

As an FYI, the test suite on master appears to be broken with 23 failures. This adds two passing tests with no regressions.

**Comment by clason** [comment]
Yes, I know; this fork is just a band-aid on what was there before. (Note that all failing tests are for _invalid_ syntax; the error is now just somewhere else in the tree.)

**Comment by amaanq** [comment]
nice, thanks

**Comment by amaanq** [comment]
nice, thanks

**Pull request merged**
